export const SIGN_OUT = 'streams/SIGN_OUT'
export const SIGN_IN = 'streams/SIGN_IN'
export const CREATE_STREAM = 'streams/CREATE_STREAM'
export const FETCH_STREAMS = 'streams/FETCH_STREAMS'
export const FETCH_STREAM = 'streams/FETCH_STREAM'
export const EDIT_STREAM = 'streams/EDIT_STREAM'
export const DELETE_STREAM = 'streams/DELETE_STREAM'